### ISSUE TITLE
compilation failed Centos 6.7

### ISSUE THREAD

**Issue by markushk** [lucian-ilie/HISEA#1]
Hey,

I am trying to compile HISEA on our cluster:

Centos 6.7
gcc 4.9.2
boost 1.60

I get the following warnings/errors

make CXXFLAGS+="-std=c++11 -I/software/boost_lib/boost_1_60/include -L/software/boost_lib/boost_1_60_0/stage/lib"

Basic check complete
cd /software/HISEA/my_HISEA/HISEA/src/; make hisea
make[1]: Entering directory `/software/HISEA/my_HISEA/HISEA/src'
/opt/rh/devtoolset-3/root/usr/bin/g++  -std=c++11 -I/software/boost_lib/boost_1_60/include -L/software/boost_lib/boost_1_60_0/stage/lib -IUtil -IThirdParty/gzstream -IAlgorithm  /software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp -c -o Globals.o
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: narrowing conversion of ‘18446744073692774400ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
                         };
                         ^
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: narrowing conversion of ‘18446744073642442752ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: narrowing conversion of ‘18446744073441116160ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: narrowing conversion of ‘18446744072635809792ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: narrowing conversion of ‘18446744069414584320ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: narrowing conversion of ‘18446744056529682432ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: narrowing conversion of ‘18446744004990074880ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: narrowing conversion of ‘18446743798831644672ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: narrowing conversion of ‘18446742974197923840ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: narrowing conversion of ‘18446739675663040512ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: narrowing conversion of ‘18446726481523507200ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: narrowing conversion of ‘18446673704965373952ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: narrowing conversion of ‘18446462598732840960ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:48:25: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:99:33: error: too many initializers for ‘UINT_TYPE [8] {aka short unsigned int [8]}’
                                 };
                                 ^
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:99:33: warning: narrowing conversion of ‘13835058055282163712ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:99:33: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:99:33: warning: narrowing conversion of ‘17293822569102704640ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:99:33: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:99:33: warning: narrowing conversion of ‘18158513697557839872ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:99:33: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:99:33: warning: narrowing conversion of ‘18374686479671623680ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:99:33: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:99:33: warning: narrowing conversion of ‘18428729675200069632ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:99:33: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:99:33: warning: narrowing conversion of ‘18442240474082181120ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:99:33: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:99:33: warning: narrowing conversion of ‘18445618173802708992ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:99:33: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:99:33: warning: narrowing conversion of ‘18446462598732840960ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:99:33: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:134:35: error: too many initializers for ‘UINT_TYPE [8] {aka short unsigned int [8]}’
                                   };
                                   ^
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:169:35: error: too many initializers for ‘UINT_TYPE [8] {aka short unsigned int [8]}’
                                   };
                                   ^
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:169:35: warning: narrowing conversion of ‘4611686018427387903l’ from ‘long int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:169:35: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:169:35: warning: narrowing conversion of ‘14987979559889010687ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:169:35: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:169:35: warning: narrowing conversion of ‘17582052945254416383ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:169:35: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:169:35: warning: narrowing conversion of ‘18230571291595767807ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:169:35: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:169:35: warning: narrowing conversion of ‘18392700878181105663ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:169:35: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:169:35: warning: narrowing conversion of ‘18433233274827440127ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:169:35: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:169:35: warning: narrowing conversion of ‘18443366373989023743ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:169:35: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:169:35: warning: narrowing conversion of ‘18445899648779419647ul’ from ‘long unsigned int’ to ‘UINT_TYPE {aka short unsigned int}’ inside { } [-Wnarrowing]
/software/HISEA/my_HISEA/HISEA/src/Util/Globals.cpp:169:35: warning: large integer implicitly truncated to unsigned type [-Woverflow]
make[1]: *** [Globals.o] Error 1
make[1]: Leaving directory `/software/HISEA/my_HISEA/HISEA/src'
make: *** [build_src] Error 2

Am I doing something horribly wrong ?

Cheers

**Comment by nkhiste** [comment]
Have you changed the make file in any way? It seems you removed some of the options we pass to make command.

It seems you want to pass path of boost library. Do not change the top level make file. Add it in the  INCLUDE_DIR in ./src/Makefile. Just do it similar to other include directories.

Let me know if that does not help.

**Comment by markushk** [comment]
that did the trick, thanks alot !
